print("Bien venue dans le programme, tu me donneras 3 nombres et je te donnerai le minimum et le maximum")
print("Donne moi le premier : ")
n1=float(input())
print("donne moi le deuxième : ")
n2=float(input())
print("Le troisième : ")
n3=float(input())
print("la plus petite valeur est "+str(min(n1,n2,n3)))
print("la plus grande valeur est "+str(max(n1,n2,n3)))