print("saisis ta première note d'évaluation sur 20 : ")
n1 = float(input())
print("la deuxième : ")
n1 = float(input())
print("la troisième : ")
n1 = float(input())
print("la quatrième : ")
n1 = float(input())
print("la cinquième : ")
n1= float(input())
print("la moyenne de ces nombres est de "+str(n1/5) + ("/20"))
